In [ ]:
sns.set_theme(style_"whitegrid)
plt.figure(figsize=(14,6))
sns.kdeplot(df["A"],fill=True,label="A")
sns.kdeplot(df["A"],fill=True,label="A")
sns.kdeplot(df["A"],fill=True,label="A")
plt.xlabel("Sales")
plt.ylabel("Density")
plt.title("Kernel Density Plot")
plt.legend()
plt.show()

In [10]:
import pandas as pd
import numpy as np

In [21]:
comp_A=[480,500,510,520,530,540,550,570,580,590,600,560,610,620,630,60,650,660]
comp_B=[300,320,340,370,390,400,380,400,390,430,440,500,480,540,600,850,1200,1220]
comp_C=[50,100,250,700,750,800,740,750,760,780,790,810,800,810,820,830,840,900]
df=pd.DataFrame({
    "A":comp_A,
    "B":comp_B,
    "C":comp_C 
})
df

      A     B    C
0   480   300   50
1   500   320  100
2   510   340  250
3   520   370  700
4   530   390  750
5   540   400  800
6   550   380  740
7   570   400  750
8   580   390  760
9   590   430  780
10  600   440  790
11  560   500  810
12  610   480  800
13  620   540  810
14  630   600  820
15   60   850  830
16  650  1200  840
17  660  1220  900

In [23]:
comp_A.sort()
comp_B.sort()
comp_C.sort()

In [29]:
dff=pd.DataFrame({
    "A":comp_A,
    "B":comp_B,
    "C":comp_C 
})
dff

      A     B    C
0    60   300   50
1   480   320  100
2   500   340  250
3   510   370  700
4   520   380  740
5   530   390  750
6   540   390  750
7   550   400  760
8   560   400  780
9   570   430  790
10  580   440  800
11  590   480  800
12  600   500  810
13  610   540  810
14  620   600  820
15  630   850  830
16  650  1200  840
17  660  1220  900

In [32]:
q1=np.quantile(dff,0.25)
q2=np.quantile(dff,0.50)
q3=np.quantile(dff,0.75)
print(q1)
print(q2)
print(q3)

432.5
575.0
757.5

In [33]:
Iqr_val = q3-q1
Iqr_val

np.float64(325.0)

In [36]:
lower_boundary = q1-1.5*Iqr_val
upper_boundary = q3+1.5*Iqr_val
print(lower_boundary)
print(upper_boundary )
outlier = dff[(dff<lower_boundary) | (dff>upper_boundary)]
outlier

-55.0
1245.0

     A   B   C
0  NaN NaN NaN
1  NaN NaN NaN
2  NaN NaN NaN
3  NaN NaN NaN
4  NaN NaN NaN
5  NaN NaN NaN
6  NaN NaN NaN
7  NaN NaN NaN
8  NaN NaN NaN
9  NaN NaN NaN
10 NaN NaN NaN
11 NaN NaN NaN
12 NaN NaN NaN
13 NaN NaN NaN
14 NaN NaN NaN
15 NaN NaN NaN
16 NaN NaN NaN
17 NaN NaN NaN

## Correct Way

In [37]:
import pandas as pd
import numpy as np

In [38]:
comp_A=[480,500,510,520,530,540,550,570,580,590,600,560,610,620,630,60,650,660]
comp_B=[300,320,340,370,390,400,380,400,390,430,440,500,480,540,600,850,1200,1220]
comp_C=[50,100,250,700,750,800,740,750,760,780,790,810,800,810,820,830,840,900]
df=pd.DataFrame({
    "A":comp_A,
    "B":comp_B,
    "C":comp_C 
})
df

      A     B    C
0   480   300   50
1   500   320  100
2   510   340  250
3   520   370  700
4   530   390  750
5   540   400  800
6   550   380  740
7   570   400  750
8   580   390  760
9   590   430  780
10  600   440  790
11  560   500  810
12  610   480  800
13  620   540  810
14  630   600  820
15   60   850  830
16  650  1200  840
17  660  1220  900

### For A

In [82]:
a=df["A"].sort_values()
print(a)
q1=np.quantile(a,0.25)
q2=np.quantile(a,0.50)
q3=np.quantile(a,0.75)
print("Q1:",q1)
print("Q2:",q2)
print("Q3:",q3)
iqr=q3-q1
print("IQR:",iqr)
lb = q1-1.5*iqr
ub = q3+1.5*iqr
print("LB:",lb)
print("UB:",ub)

15     60
0     480
1     500
2     510
3     520
4     530
5     540
6     550
11    560
7     570
8     580
9     590
10    600
12    610
13    620
14    630
16    650
17    660
Name: A, dtype: int64
Q1: 522.5
Q2: 565.0
Q3: 607.5
IQR: 85.0
LB: 395.0
UB: 735.0

In [83]:
outlier = a[(a<lb) | (a>ub)]
print("Outlier:",outlier)

Outlier: 15    60
Name: A, dtype: int64

## For B

In [76]:
b=df["B"].sort_values()
print(b)
q1=np.quantile(b,0.25)
q2=np.quantile(b,0.50)
q3=np.quantile(b,0.75)
print("Q1:",q1)
print("Q2:",q2)
print("Q3:",q3)
iqr2=q3-q1
print("IQR:",iqr2)
lb2 = q1-1.5*iqr2
ub2 = q3+1.5*iqr2
print("LB:",lb2)
print("UB:",ub2)

0      300
1      320
2      340
3      370
6      380
4      390
8      390
5      400
7      400
9      430
10     440
12     480
11     500
13     540
14     600
15     850
16    1200
17    1220
Name: B, dtype: int64
Q1: 382.5
Q2: 415.0
Q3: 530.0
IQR: 147.5
LB: 161.25
UB: 751.25

In [78]:
outlier2 = b[(b<lb2) | (b>ub2)]
print("Outlier:",outlier2)

Outlier: 15     850
16    1200
17    1220
Name: B, dtype: int64

## For C

In [74]:
c=df["C"].sort_values()
print(c)
q1=np.quantile(c,0.25)
q2=np.quantile(c,0.50)
q3=np.quantile(c,0.75)
print("Q1:",q1)
print("Q2:",q2)
print("Q3:",q3)
iqr3=q3-q1
print("IQR:",iqr3)
lb3 = q1-1.5*iqr3
ub3 = q3+1.5*iqr3
print("LB:",lb3)
print("UB:",ub3)

0      50
1     100
2     250
3     700
6     740
4     750
7     750
8     760
9     780
10    790
5     800
12    800
11    810
13    810
14    820
15    830
16    840
17    900
Name: C, dtype: int64
Q1: 742.5
Q2: 785.0
Q3: 810.0
IQR: 67.5
LB: 641.25
UB: 911.25

In [75]:
outlier3 = c[(c<lb3) | (c>ub3)]
print("Outlier:",outlier3)

Outlier: 0     50
1    100
2    250
Name: C, dtype: int64